### PR TITLE
fix backticks in inline code (fixes #312)

### LINKED ISSUE #312: Single backtick in inline code
``` sh
$ marked
`` ` ``
^D
<p><code>` </code></p>
```

There is a remaining white space after the backtick that shouldn't be there !

http://daringfireball.net/projects/markdown/syntax#code
At the "A single backtick in a code span" part, the output doesn't have that trailing space.

### PR DESCRIPTION
**Pull request by Feder1co5oave**
Fixes #312.
Some simple test cases are included in linked issue.

### CODE REVIEW

**Comment by joshbruce** [comment]
Closing as having merge conflicts, stale, tagging with #983

**Comment by Feder1co5oave** [comment]
I will add some tests even if it is pointless since whitespace is not checked when testing.

**Comment by joshbruce** [comment]
Don't know. Stupid question time, just to confirm: You did push/sync? (That happened to me when I first realized you could push changes to a PR.)

I can reopen, if you would like. I was going to do it without checking in, but didn't want to get in the way of you testing something based on the "stupid question".

**Comment by joshbruce** [comment]
Quick search isn't showing me any documentation from GitHub that that block this feature if changes are made to PR that is closed....gotta start heading home. Let me know.

**Comment by Feder1co5oave** [comment]
Thing is, I don't see anywhere on this issue page the usual "add commits to branch <pr branch> to add changes to the PR" (something along those lines), so I guess this is not working as I expected but I can't see why. 

(yes, I pushed and the new commits showed up on my fork repo, but not here)

Well, I'll open a new pr. I've also rebased so history looks more tidy.

**Pull request closed without merging**
