### PR TITLE
V0.3.9

### LINKED ISSUE #555: Vulnerable to regular expression denial of service (ReDoS) when certain types of input are passed in to be parsed.
Not sure if already being addressed, but my [David DM](https://david-dm.org/mauvm/documark) shows "SECURITY VULNERABILITIES IN DEPENDENCIES" because of Marked v0.3.3.

It links to this article: https://nodesecurity.io/advisories/marked_redos (CVE-PENDING). Which states:

> Marked 0.3.3 and earlier is vulnerable to regular expression denial of service (ReDoS) when certain types of input are passed in to be parsed.

### LINKED ISSUE #925: Cross-site Scripting (XSS) via URI
Browsers support both lowercase and uppercase `x` in hexadecimal form of HTML character entity (tested on Chromium && FF).
But marked unescape only lowercase:
```js
// https://github.com/chjj/marked/blob/master/lib/marked.js#L1096-L1108

function unescape(html) {
	// explicitly match decimal, hex, and named HTML entities 
  return html.replace(/&(#(?:\d+)|(?:#x[0-9A-Fa-f]+)|(?:\w+));?/g, function(_, n) {
    n = n.toLowerCase();
    if (n === 'colon') return ':';
    if (n.charAt(0) === '#') {
      return n.charAt(1) === 'x'
        ? String.fromCharCode(parseInt(n.substring(2), 16))
        : String.fromCharCode(+n.substring(1));
    }
    return '';
  });
}
```

This allow attacker to create link with javascript code.
For example, this code:
```js
var marked = require('marked');
marked.setOptions({
  renderer: new marked.Renderer(),
  sanitize: true
});

text = `
lower[click me](javascript&#x3a;...)lower
upper[click me](javascript&#X3a;...)upper
`;

console.log(marked(text));
```

Will render:
```html
<p>lowerlower
upper<a href="javascript&#X3a;...">click me</a>upper</p>
```

Browser example: https://www.buglloc.com/marked.html
Tested on Marked v0.3.6 + Chromium 60.0.3112.90 and Firefox 55.0.1

### LINKED ISSUE #926: Cross-site Scripting (XSS) via autolink (require disabled mangling)
When mangling is disabled via option `mangle` marked don't escape target href. This allow attacker to inject arbitrary html-event into resulting `a` tag.

For example, this JS code:
```js
var marked = require('marked');
marked.setOptions({
  renderer: new marked.Renderer(),
  sanitize: true,
  mangle: false
});

text = `
<bar"onclick="alert('XSS')"@foo>
`;

console.log(marked(text));
```

Will render:
```html
<p><a href="mailto:bar"onclick="alert('XSS')"@foo">bar"onclick="alert('XSS')"@foo</a></p>
```

Tested on marked v0.3.6
Online demo: http://www.buglloc.com/marked-mangle.html

Fixes #925

### PR DESCRIPTION
**Pull request by UziTech**
This combines #958 (merge from 8fold-marked) and #974 (fix failing tests) and other fixes

All tests are passing 🎉 and minification is done.

@joshbruce We should try to get this pushed out to alleviate nsp https://nodesecurity.io/advisories/531

Fixes #958 
Fixes #974

Fixes #555 - see comment
Fixes #925 - see comment
Fixes #926 - see comment

### CODE REVIEW

**Comment by joshbruce** [comment]
This may sound strange, but will do in the morning.

You're awesome! Thanks to both @UziTech and @KostyaTretyak - 0.3.9 release party tomorrow. :)

**Comment by KostyaTretyak** [comment]
Cool, but why not megre this [Pull Request](https://github.com/chjj/marked/pull/975)? Simple code there, and performance improvements are easy to verify with the `npm run bench`.

**Comment by joshbruce** [comment]
@KostyaTretyak - Fair question. I will, just not tonight I'm fried and am wondering if we might be able to leverage the power of GitHub a little more.

I've added the "Fixes" keyword with reference to both PRs this one covers. This should tell GitHub to close those PRs automatically when I perform the merge. I'm wondering if there are any other PRs or tickets that are open that we can add to this list.

Kill two birds (close duplicative issues and PRs) with one stone.

For example, @KostyaTretyak, I don't remember exactly, but I think you had an Issue open related to your PR (I don't remember if I closed it). If we add it to the list, we get the reference & the closing. 

Not asking y'all to go through issues and PRs exactly, just wondering if you know any off the top of your heads that we should add that are covered by this unified PR besides those already listed?

@UziTech

**Comment by joshbruce** [comment]
ps. @KostyaTretyak - sorry, think I missed the point of your question. I think what @UziTech was trying to do was finish off the split we did for a month or so. My fork is already at 0.3.9. Once we get Marked up to the same, I think we can really start looking at the other PRs and package some "sane" releases together. (Focusing on the security vulnerabilities right now as well. Marked is getting flagged in a lot of places.)

**Comment by joshbruce** [comment]
Does this also address #555 ?

**Comment by UziTech** [comment]
looks like #555 was already fixed in v0.3.4

I pushed fixes for #925 and #926

**Comment by joshbruce** [comment]
All right, seriously, I should sleep. Thanks again to you both.

Happy holidays!

Oh, what are the targets for `npm bench`? never used it before.

**Comment by KostyaTretyak** [comment]
In [package.json](https://github.com/chjj/marked/blob/753a7bd04a5067fef60e9dfc9acde61d1251d7ea/package.json#L35) there command `bench`:

```text
"bench": "node test --bench"
```

Its using for `npm run bench`, but for `marked` it's errored [because this](https://github.com/chjj/marked/blob/753a7bd04a5067fef60e9dfc9acde61d1251d7ea/test/index.js#L532):

```js
if (!module.parent) {
  process.title = 'marked';
  process.exit(main(process.argv.slice()) ? 0 : 1);
} else {
  exports = main;
  exports.main = main;
  exports.runTests = runTests;
  exports.runBench = runBench;
  exports.load = load;
  exports.bench = bench;
  module.exports = exports;
}
```

**Pull request merged**
