### PR TITLE
typographic switch

### PR DESCRIPTION
**Pull request by iamstarkov**
Hey, I'm using your markdown compiler for a while and want to say thank you for it!

Btw, I’m little obsessed with typography and wrote a bunch of small, full tested and safe to use typographic modules. That’s why I’m wondering will you prefer to delegate typography to 3rd party packages and concentrate marked’s development only on parsing and compiling?

if no, it's fine, I understand. If yes, check out this pull-request and feel free to comment and ask me anything. Will look forward for your response.

PS. My origin idea of this pull-request was that compiler should not be responsible for typography, it should do well parsing and compiling and what do you think?

### CODE REVIEW

**Comment by matmuchrapna** [comment]
hey, hey =) is anybody here? :ghost:

**Comment by matmuchrapna** [comment]
polite ping =)

**Comment by matmuchrapna** [comment]
@chjj is project dead and deprecated?

**Comment by JCMais** [comment]
@matmuchrapna Project is probably dead, given the number of open issues and pull requests.

**Comment by chjj** [comment]
If you want to pull those modules' code into marked, I'll reconsider it, but I really don't want marked to have that many dependencies since it should be used easily in the browser as well.

**Comment by iamstarkov** [comment]
All the deps are one-liners, it’s not big deal, it’s even not _small_ deal

**Comment by iamstarkov** [comment]
on the other side, you will have benefit in form of delegating typography to 3rd party plugins

**Comment by chjj** [comment]
@iamstarkov, marked has no dependencies for a reason. It shouldn't require a build for the browser. A lot of people just `<script src="raw.github.com/.../marked.js>` in their html. There shouldn't be any requires. If they're just one-liners that's great. Let's include them inline.

**Comment by iamstarkov** [comment]
didn’t about how consumers are using marked, seems reasonable.

> If they're just one-liners that's great. Let's include them inline.

okay, it will work. how to deal with responsibility delegation here?

**Pull request closed without merging**
