### PR TITLE
Expose an option for rendering image/link URLs relative to a base

### LINKED ISSUE #320: GFM: Absolutify relative links in markup files
Hi,

in https://github.com/isaacs/npm-www/issues/517 @sindresorhus is mentioning support from GFM for relative image paths (https://github.com/blog/1395-relative-links-in-markup-files)

In npm-www we are taking the `readme.md`, which is often hosted on GitHub, too and are rendering markdown for the detail page of the package from it. Sometimes the readme makes use of the relative-img-path-feature from GitHub (see issue).

Turns out, that supporting converts (from relative paths to absolute ones) for images which are embedded html is not that easy: the custom html renderer is ignoring the img tag (https://github.com/chjj/marked/blob/master/lib/marked.js#L50) and they are included in the `paragraph`-callback with all other tags.

In order to support relative img paths from GFM on npm-www it would be nice to have a  easy way to convert the paths at the rendering stage or before.

### PR DESCRIPTION
**Pull request by gibson042**
Fixes #320

### CODE REVIEW

**Comment by jpsfs** [comment]
This will be very helpful when merged!

**Comment by cheungnj** [comment]
@gibson042 Could you submit this PR to the unofficial fork: https://github.com/8fold/marked? It looks like this project isn't really being maintained anymore according to https://github.com/chjj/marked/issues/938

**Comment by UziTech** [comment]
this was merged in v0.3.9 and can be closed

**Comment by joshbruce** [comment]
Closing as completed. Thanks!

**Pull request closed without merging**
