### PR TITLE
added data: link fix to prevent xss

### PR DESCRIPTION
**Pull request by matt-**

### CODE REVIEW

**Comment by matt-** [comment]
@chjj  I added this along the same lines as the javascript: xss. Can we version bump and push this?

**Comment by paulirish** [comment]
Heya @matt- 
Can we expect a version bump out soon? We're interested in this fix and would like to avoid depending on a specific github commit if possible. ;)

**Comment by matt-** [comment]
No idea thats up to @chjj.

**Comment by paulirish** [comment]
k. thank you!

@chjj can you add the other contributors here to the npm package so they can publish as well?

**Comment by guypod** [comment]
@paulirish note in the meantime you can also use a Snyk patch (see the bottom of https://snyk.io/vuln/npm:marked:20170112). 

When we initially reported the problem it had no fix, but once Matt created a fix we captured it as a Snyk patch too. More about Snyk patches here: https://snyk.io/docs/security

**Comment by zhangbobell** [comment]
Thank you very much to send this pull request, it's help me a lot!

**Pull request merged**
