### PR TITLE
#588 Add option to allow json output instead of a string

### PR DESCRIPTION
**Pull request by 4ok**

### CODE REVIEW

**Comment by chjj** [comment]
This changes a lot and adds a lot of method calls. Is the overhead worth the benefit?

**Comment by 4ok** [comment]
I have no idea how to do differently.

The rendering result was originally conceived in order to return a string. To return result in any formats, were invented such a decision. In addition this solution is extensible.

Moreover, the method call not greatly affect the speed of execution.

**Comment by 4ok** [comment]
Look module [markdown-bemjson](https://github.com/bem-incubator/markdown-bemjson), it based on forked marked.

**Comment by joshbruce** [comment]
Closing due to merge conflicts, stale, missing tests, and beyond scope for the focus per #956.

**Pull request closed without merging**
