### PR TITLE
Add multiple headers for tables

### PR DESCRIPTION
**Pull request by killall5**
This patch add:
- multiple header rows for tables
- add colspan for cells
- unify nptable & table code

### CODE REVIEW

**Comment by joshbruce** [comment]
#980

**Comment by joshbruce** [comment]
Pretty sure we want to close this as I'm pretty sure "unknown repository" means abandoned. @matt- @UziTech

**Comment by lhf552004** [comment]
Hi @killall5 , It's very glad to see this PR. Is it now avaliable in current Marked? And how to use it?
Thanks

**Comment by UziTech** [comment]
No this PR was closed without being merged.

**Comment by lhf552004** [comment]
> No this PR was closed without being merged.

Hi @UziTech ,  Is there any way to achieve this funtionality? about colspan and rowspan for table.

**Comment by UziTech** [comment]
According to the [GFM spec](https://github.github.com/gfm/#tables-extension-) 

> A table is an arrangement of data with rows and columns, consisting of a single header row, a delimiter row separating the header from the data, and zero or more data rows.

The only way to have multiple header rows or colspan and rowspan is with html. [demo](https://marked.js.org/demo/?text=%3Ctable%3E%0A%20%20%3Cthead%3E%0A%20%20%20%20%3Ctr%3E%0A%20%20%20%20%20%3Cth%3Ea%3C%2Fth%3E%0A%20%20%20%20%20%3Cth%3Eb%3C%2Fth%3E%0A%20%20%20%20%3C%2Ftr%3E%0A%20%20%20%20%3Ctr%3E%0A%20%20%20%20%20%3Cth%3Ec%3C%2Fth%3E%0A%20%20%20%20%20%3Cth%3Ed%3C%2Fth%3E%0A%20%20%20%20%3C%2Ftr%3E%0A%20%20%3C%2Fthead%3E%0A%20%20%3Ctbody%3E%0A%20%20%20%20%3Ctr%3E%0A%20%20%20%20%20%3Ctd%3Etd%3C%2Ftd%3E%0A%20%20%20%20%20%3Ctd%20rowspan%3D%222%22%3Erowspan%202%3C%2Ftd%3E%0A%20%20%20%20%3C%2Ftr%3E%0A%20%20%20%20%3Ctr%3E%0A%20%20%20%20%20%3Ctd%3Etd%3C%2Ftd%3E%0A%20%20%20%20%3C%2Ftr%3E%0A%20%20%20%20%3Ctr%3E%0A%20%20%20%20%20%3Ctd%20colspan%3D%222%22%3Ecolspan%202%3C%2Ftd%3E%0A%20%20%20%20%3C%2Ftr%3E%0A%20%20%3C%2Ftbody%3E%0A%3C%2Ftable%3E&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

**Pull request closed without merging**
