### PR TITLE
Revert 98ac7a4 and a477d1d

### PR DESCRIPTION
**Pull request by KostyaTretyak**
See https://github.com/chjj/marked/issues/1006

### CODE REVIEW

**Comment by joshbruce** [comment]
@Feder1co5oave: Real quick, this looks good to me, but I would like a second pair of eyes - just to be able to add it to the release we are trying to do today.

Thank you @KostyaTretyak!

**Comment by Feder1co5oave** [comment]
NO WAIT

**Comment by Feder1co5oave** [comment]
Looks like this won't solve #1006. Check out my last comments.

**Comment by KostyaTretyak** [comment]
Now marked works this way:

```md
`
def ?`

```

Output:

```html
<p>`</p>
<p>def ?`</p>
```

With this pull request marked output:

```html
<p><code>def ?</code></p>
```

**Comment by KostyaTretyak** [comment]
However, when we return everything as it was before https://github.com/chjj/marked/commit/98ac7a43958014832788b9d01580f394c84bfb27, then [this rule](http://spec.commonmark.org/0.28/#example-178) will not be works.

**Comment by KostyaTretyak** [comment]
However, in two of your three comments, you were wrong with the rules. Now we know that my test edits were correct, but I was incorrect when I deleted rule with blockquote from `marked.js`.

**Comment by joshbruce** [comment]
Two questions mainly for @KostyaTretyak, @Feder1co5oave, @UziTech:

1. Do we merge this before doing the release of [0.3.12](https://github.com/chjj/marked/releases/tag/untagged-fd441601fc06eba749f4)? 
2. Should we push the release off a day or two to figure this out?

**Comment by Feder1co5oave** [comment]
I believe it's better if we just revert this one, push out important security issues and in the meanwhile work on these, as you suggest @joshbruce.

@KostyaTretyak I admit I'm crossing my eyes over regexes and markdown examples, can you point out in the review what complies to the spec and what doesn't?

Thanks to both of you

**Comment by joshbruce** [comment]
@Feder1co5oave: I believe that's the best as well. Having said that, still not entirely comfortable doing the revert myself using `git revert` if this one doesn't do that. Help a brother out?

**Comment by Feder1co5oave** [comment]
You only need to merge this pr

**Comment by joshbruce** [comment]
@Feder1co5oave: Thanks, brother. Just really wanted to make sure I was looking at the right thing and understanding the conversation that was happening. :)

**Comment by joshbruce** [comment]
Text-base communication because the lowest bandwidth communication and all that. ;)

**Pull request merged**
