### PR TITLE
sort tests

### PR DESCRIPTION
**Pull request by UziTech**
Sorting tests alphabetically for more deterministic tests.

@joshbruce this was supposed to go with #1002

### CODE REVIEW

**Comment by joshbruce** [comment]
@UziTech: Interesting. This is alphabetizing the console output, yeah? Just to make sure I'm understanding...then I should probably go to sleep.

**Comment by UziTech** [comment]
And alphabetizing the way the tests are ran. So we can run tests in a specific order if we need to.

**Comment by joshbruce** [comment]
Cool. Do we have a way to run a single test case? Just curious.

**Comment by UziTech** [comment]
No we don't. Do you want me to set that up?

**Comment by joshbruce** [comment]
@UziTech: If it's not difficult, it would probably be helpful - not that it takes that long for our tests to run, of course...we just have a lot and might be easier for someone adding a new feature to test their single piece of new functionality, you know?

**Comment by UziTech** [comment]
I added running only certain tests by specifying a glob pattern

``` bash
node test --glob gfm*
```

that will only run tests that start with 'gfm'

**Comment by joshbruce** [comment]
Thanks, brother!

**Comment by joshbruce** [comment]
#746

**Pull request merged**
